name: Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        name: Setup Go Latest
        id: setup-go
        with:
          go-version: 1.21

      - uses: golangci/golangci-lint-action@v3

      - name: Test
        id: test
        run: go test -v ./...
